[package]
name = "jmc"
version = "0.1.0"
edition = "2021"

[features]
default = ["native-tls"]
native-tls = ["matrix-sdk/native-tls"]
rustls-tls = ["matrix-sdk/rustls-tls"]

[dependencies]
druid = { git = "https://github.com/linebender/druid" }
druid-widget-nursery = { git = "https://github.com/linebender/druid-widget-nursery" }
tracing-subscriber = "0.3.1"
tracing = "0.1.29"

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
default-features = false
features = [
    "encryption",
    "sled_cryptostore",
    "sled_state_store",
]

[patch.crates-io.futures-locks]
git = "https://github.com/jplatte/futures-locks"
branch = "tmp"

[patch."https://github.com/linebender/druid".druid]
git = "https://github.com/jplatte/druid"
branch = "hacky-password-support"
